// GET STUDENT  

export const GET_STUDENT_PROGESS = "GET_STUDENT_PROGESS"
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
export const GET_STUDENT_ERROR = "GET_STUDENT_ERROR"

// POST STUDENT

export const POST_STUDENT_PROGESS = "POST_STUDENT_PROGESS"
export const POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS"
export const POST_STUDENT_ERROR = "POST_STUDENT_ERROR"

// DELETE STUDENT

export const DELETE_STUDENT_PROGESS = "DELETE_STUDENT_PROGESS"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR"

// UPDATE STUDENT

export const UPDATE_STUDENT_PROGESS = "UPDATE_STUDENT_PROGESS"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR"