// GET STUDENT  

export const GET_STUDENT_PROGESS = "GET_STUDENT_PROGESS"
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
export const GET_STUDENT_ERROR = "GET_STUDENT_ERROR"

// POST STUDENT

export const POST_STUDENT_PROGESS = "POST_STUDENT_PROGESS"
export const POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS"
export const POST_STUDENT_ERROR = "POST_STUDENT_ERROR"