// GET STUDENT  // STUDENT

export const GET_STUDENT_PROGESS = "GET_STUDENT_PROGESS"
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
export const GET_STUDENT_ERROR = "GET_STUDENT_ERROR"

// GET FACULTY  // FACULTY
export const GET_FACULTY_PROGESS = "GET_FACULTY_PROGESS"
export const GET_FACULTY_SUCCESS = "GET_FACULTY_SUCCESS"
export const GET_FACULTY_ERROR = "GET_FACULTY_ERROR"

// POST FACULTY

export const POST_FACULTY_PROGESS = "POST_FACULTY_PROGESS"
export const POST_FACULTY_SUCCESS = "POST_FACULTY_SUCCESS"
export const POST_FACULTY_ERROR = "POST_FACULTY_ERROR"

// DELETE FACULTY

export const DELETE_FACULTY_PROGESS = "DELETE_FACULTY_PROGESS"
export const DELETE_FACULTY_SUCCESS = "DELETE_FACULTY_SUCCESS"
export const DELETE_FACULTY_ERROR = "DELETE_FACULTY_ERROR"