// GET SUBADMIN

export const GET_SUBADMIN_PROGESS = "GET_SUBADMIN_PROGESS"
export const GET_SUBADMIN_SUCCESS = "GET_SUBADMIN_SUCCESS"
export const GET_SUBADMIN_ERROR = "GET_SUBADMIN_ERROR"

// POST SUBADMIN

export const POST_SUBADMIN_PROGESS = "POST_SUBADMIN_PROGESS"
export const POST_SUBADMIN_SUCCESS = "POST_SUBADMIN_SUCCESS"
export const POST_SUBADMIN_ERROR = "POST_SUBADMIN_ERROR"

// DELETE SUBADMIN

export const DELETE_SUBADMIN_PROGESS = "DELETE_SUBADMIN_PROGESS"
export const DELETE_SUBADMIN_SUCCESS = "DELETE_SUBADMIN_SUCCESS"
export const DELETE_SUBADMIN_ERROR = "DELETE_SUBADMIN_ERROR"